export enum Industry {
  TECHNOLOGY = 'TECHNOLOGY',
  FOOD = 'FOOD',
  AUTOMOTIVE = 'AUTOMOTIVE',
  EDUCATION = 'EDUCATION',
  HEALTHCARE = 'HEALTHCARE',
  FINANCE = 'FINANCE',
  RETAIL = 'RETAIL',
  MANUFACTURING = 'MANUFACTURING',
  OTHER = 'OTHER',
}
